### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by jpmckearin** [iFaxity/SoundCloud.Desktop#1]
I might be interested in contributing to this project but it looks as if you're using a closed source audio library that's not includes in the source repo (Un4seen BASS as well as a closed source wrapper, BASS.NET.) Also, you have references some seemingly home-grown FaxLib and FaxUi libraries which aren't included in the source repo. Did you have any plans to move onto open source alternative(s) or disclose the homegrown libraries?

**Comment by iFaxity** [comment]
Yes you're correct my good sir. I chose to use bass.net because it's an amazing library and i have been working towards using/creating an alternative.

However the libraries FaxLib and FaxUI is homegrown by me and includes shorthands of stuff i need. Including the window design itself. They are not published yet because this application is testing these libraries. I could make a repo for both of these if you would like it.

Also i haven't been able to do anything to this application in some time as i'm studying and now there are multiple tests. I will begin once this has subdued. 

I would like it if you contributed to make this better and to fix annoying bugs.

**Comment by iFaxity** [comment]
I have made a repo for both FaxLib and FaxUI here. 
https://github.com/iFaxity/FaxLib

It's Open Source aswell. Though the version here is not the same as in SoundStreamer because it's updated more frequently. Also some of the updates are experimental and i use it in the developer versions of SoundStreamer (still not updated to the repo).
