### ISSUE TITLE
Hey guy!

### ISSUE THREAD

**Issue by Suburbanno** [iFaxity/SoundCloud.Desktop#3]
Update?

**Comment by iFaxity** [comment]
Actually, i decided about a year ago to not continue working on the current program any longer because it was getting cluttered and the project was getting messy.

However i decided to not give up on the program and started working some other prototypes in my spare time, when i have spare time. I have been working on other projects as well and the prototypes kind of got pushed aside. The successful prototype included using Electron.

That app is working quite good (it plays songs/playlists, shows stream feed, facebook/google login, .etc). On Windows, and Mac at least, the projects structure is also amazing. But i have not decided to release a test version yet because it is still very buggy.

So there is an update coming...but i'm not really sure when. Certainly not this year. Probably not in the beginning of the next either. A test version could come out, but it depends on the demand of an update.

A peek of the app running on Mac is shown below.

![image](https://cloud.githubusercontent.com/assets/9090703/21406823/cf5f9676-c7cd-11e6-9ae6-c31cd248f6e1.png)

**Comment by Suburbanno** [comment]
oh, thanks.
